### PR TITLE
Make Werror interface

### LINKED ISSUE #48: Make werror composable and duck-typed
## What happened?

Right now, werrors are tied to a single, private implementation of `werror`. This is shown clearly by the `Convert` function:

```go
func Convert(err error) error {
	if err == nil {
		return err
	}
	switch err.(type) {
	case *werror:
		return err
	default:
		return newWerror("", err)
	}
}
```

Here, we determine if something is a werror based on its type rather than an interface. This has implications for things like generated conjure errors, which can implement many (e.g., `error`, `ParamStorer`), but not all of the behaviors that make something a werror. That means to get have nice things like stack traces captured on initialization, we would need a to convert them to conjure errors rather than returning typed errors.

## What did you want to happen?

Define a `Werror` interface that defines the expected behavior of a werror, and then treat any implementation the same.

```go
type Werror interface {
    error
    ParamStorer
    Stacker // something to handle stacktrace behaviors
}

...

func Convert(err error) error {
	if err == nil {
		return err
	}
	switch err.(type) {
	case Werror:
		return err
	default:
		return newWerror("", err)
	}
}

```

This allows us to, e.g., implement Werror in generated conjure errors without requiring Conjure to know anything about witchcraft-go-error itself. The conjure error would implement the same behaviors (e.g., capturing the stack trace and implementing the interface to retrieve) and we would have all the same nice things without needing a conversion to make it a real werror.

### PR DESCRIPTION
**Pull request by asanderson15**
## After this PR

==COMMIT_MSG==
Export public Werror interface, enabling additional implementations (e.g., conjure-go) that work seamlessly with the existing w-g-e ecosystem.
==COMMIT_MSG==

Fixes #48 

## Possible downsides?

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-error/49)

### CODE REVIEW

File: werror.go [hunk 1]
```diff
@@ -164,31 +166,34 @@ func visitErrorParams(err error, visitor func(k string, v interface{}, safe bool
...
+		if ps, ok := currErr.(wparams.ParamStorer); ok {
+			for k, v := range ps.SafeParams() {
+				visitor(k, v, true)
+			}
+			for k, v := range ps.UnsafeParams() {
+				visitor(k, v, false)
 			}
-			continue
-		}
-		for k, v := range we.params {
```
Comment (asanderson15) [inline werror.go:181]: we no longer need to special case `(*werror)` here

File: werror.go [hunk 2]
```diff
@@ -232,90 +237,113 @@ func (e *werror) Cause() error {
...
+	return e.stack
+}
+
+// Message returns the message string for this error or nil if there is none.
+func (e *werror) Message() string {
+	return e.message
+}
+
 func (e *werror) SafeParams() map[string]interface{} {
-	safe, _ := ParamsFromError(e)
```
Comment (asanderson15) [inline werror.go:236]: Because we no longer special-case `*werror`s in `ParamsFromError`, we implement this here.

File: werror.go [hunk 3]
```diff
@@ -232,90 +237,113 @@ func (e *werror) Cause() error {
...
 	return unsafe
 }
 
 // Format formats the error using the provided format state. Delegates to stored error.
 func (e *werror) Format(state fmt.State, verb rune) {
+	FormatWerror(e, state, verb)
+}
+
+// FormatWerror formats a Werror using the provided format state.
+func FormatWerror(err Werror, state fmt.State, verb rune) {
```
Comment (asanderson15) [inline werror.go]: This allows future `Werror` implementations to share the formatting logic with the existing `werror` type, which should help ensure consistency.

**Comment by asanderson15** [comment]
Marking ==DO_NOT_MERGE== until I've validated by implementing this in conjure-go.

File: werror.go [hunk 4]
```diff
@@ -232,90 +237,114 @@ func (e *werror) Cause() error {
...
+
+// Message returns the message string for this error.
+func (e *werror) Message() string {
+	return e.message
+}
+
 func (e *werror) SafeParams() map[string]interface{} {
-	safe, _ := ParamsFromError(e)
+	safe := make(map[string]interface{})
+	for k, v := range e.params {
```
Comment (tabboud) [inline werror.go:256]: note: I wonder why we don't just store the params in 2 separate fields (safe/unsafe) rather than have to go through them to check the state. I suppose either way we would have to loop through to return a copy 🤷‍♂️

File: werror.go (hunk 3 above)
Comment (tabboud) [reply werror.go]: nit: How about making this just `Format` given it's in the `werror` pkg and it takes in a `Werror` as the first param.
```go
werror.Format(...)
// vs
werror.FormatWerror(...)
```

File: stacktrace.go [hunk 5]
```diff
@@ -7,7 +7,18 @@ import (
...
 )
 
-func callers() *stack {
+var _ StackTrace = (*stack)(nil)
+
+type StackTrace interface {
+	fmt.Formatter
+}
+
+type StackTracer interface {
```
Comment (tabboud) [inline stacktrace.go:18]: Mind adding doc comments to this and `StackTrace` above, since I can see it being confusing at first what they are used for.
The `StackTracer` is more of a provider than an actual tracer, given it provides the behavior to get a stacktrace formatter.

**Review by tabboud — COMMENTED** [review]
Generally looks good to me

File: werror.go (hunk 4 above)
Comment (asanderson15) [reply werror.go:256]: Agreed. Think this is just old code. I wanted to clean it up, but didn't want to lump that into this PR.

File: werror.go (hunk 3 above)
Comment (asanderson15) [reply werror.go]: 👍 Done.

File: stacktrace.go (hunk 5 above)
Comment (asanderson15) [reply stacktrace.go:18]: Done.

File: werror.go (hunk 4 above)
Comment (bmoylan) [reply werror.go:256]: It looks like the intention is to avoid having the same key in both maps, but I'm not sure whether that's in a spec somewhere or just a decision made a long time ago

**Review by tabboud — APPROVED** [review]

File: werror.go (hunk 4 above)
Comment (asanderson15) [reply werror.go:256]: I realized this is actually incorrect as updated - it's not documented or tested, but the existing behavior is to recursively pull all params from any underlying causes as well, not just this error. Will fix, document, and add tests.

File: changelog/@unreleased/pr-49.v2.yml [hunk 6]
```diff
@@ -0,0 +1,5 @@
+type: Feature
```
Comment (bmoylan) [inline changelog/@unreleased/pr-49.v2.yml]: lowercase F

File: stacktrace.go [hunk 7]
```diff
@@ -7,7 +7,20 @@ import (
...
+	fmt.Formatter
+}
+
+// StackTracer provides the behavior necessary to retrieve a StackTrace formatter.
+type StackTracer interface {
+	StackTrace() StackTrace
+}
+
+// NewStackTrace creates a new StackTrace, constructed by collecting program counters from runtime callers.
+func NewStackTrace() StackTrace {
```
Comment (bmoylan) [inline stacktrace.go:23]: now that this is exported, it might be called from utilities that add an arbitrary number of extra stack frames. Maybe we want a `skip int` argument and below do `4+skip` or whatever the math ends up being. That way the wrapping functions don't show up in the stacktraces

File: werror_test.go [hunk 8]
```diff
@@ -560,3 +560,25 @@ func TestWrapPullsOutParamsFromContext(t *testing.T) {
...
 }
+
+func TestSafeParams(t *testing.T) {
+	err := werror.Error("first", werror.SafeParam("key", "value"))
+	err2 := werror.Wrap(err, "second", werror.SafeParam("key2", "value2"))
+	err3 := werror.Wrap(err2, "second", werror.SafeParam("key3", "value3"))
+	assert.Equal(t, map[string]interface{}{"key": "value", "key2": "value2"}, err2.(werror.Werror).SafeParams())
+	assert.Equal(t, map[string]interface{}{"key": "value", "key2": "value2", "key3": "value3"}, err3.(werror.Werror).SafeParams())
+
+	err4 := werror.Wrap(err3, "second", werror.SafeParam("key", "value4"))
```
Comment (bmoylan) [inline werror_test.go:573]: nit could you add a short comment above these saying that they're checking for the deepest param or that this param is a noop? Took me a sec to grok 😅

File: stacktrace.go (hunk 7 above)
Comment (asanderson15) [reply stacktrace.go:23]: I prefer the cleaner function for most users, so I created a second helper `NewStackTraceWithSkip` that takes `skip int` as an argument. Unfortunately, this requires duplicating the logic because having `NewStackTrace` call into `NewStackTraceWithSkip` adds an additional frame. 

I'm open to going with your suggestion of having a single function that takes a skip value if you feel strongly. Otherwise, I could also just leave this out until someone has a use case for it.

Comment (bmoylan) [reply stacktrace.go:23]: Now that it's exposed, this one can become

```go
func NewStackTrace() StackTrace {
    return NewStackTraceWithSkip(1)
}
```

Comment (asanderson15) [reply stacktrace.go:23]: lol, yes, correct

**Comment by asanderson15** [comment]
The downstream PRs are up, so this can be merged whenever it's ready.

**Review by bmoylan — APPROVED** [review]

**Review by tabboud — APPROVED** [review]
